# =============================================================================
# Golden-reference regression: the four reference models (Bering Sea + Gulf of
# Alaska, single- and multi-species) must reproduce their pinned objective
# functions. This is the committed backstop for "numeric changes need golden
# equivalence" -- any edit that moves the LIKELIHOOD fails here.
#
# It does not re-optimize, so an edit confined to the optimization path -- a
# phase order, a starting value, a bound inactive at the reference -- no longer
# fails here. tools/verify/verify-golden-cold-start.R covers that instead.
#
# The multispecies references are warm-started from their single-species MLEs
# (the predation likelihood is non-convex, so the start point selects the local
# optimum); the GOA multispecies fit uses fixed M. The parameters live in
# fixtures/golden-reference.rds, regenerated by
# tools/verify/regenerate-golden-reference.R.
#
# NOTE the second block below, "golden reference by configuration", DOES still
# cold-fit and pin objectives. Those are all BS2017SS, whose basin this file
# documents as robust (jitter spread ~1e-11), which is why they are left alone.
# =============================================================================

# The GOA reference objectives changed in 5.33.0 (goa_ss -0.0150, goa_ms -0.0030):
# GOA2018SS fleet 2 has a q prior, which is now mean-centred under bias_adjust_proc.
#
# They changed again in 5.48.0 (goa_ss -1.1445, goa_ms -0.9299): length
# compositions no longer pass through the ageing-error matrix. A length
# measurement carries no otolith reading, so the age-length key is applied to
# the true ages. GOA2018SS species 2 is the only reference with both a
# non-identity ageing-error matrix and length comps, which is why the Bering
# Sea pair is unchanged -- and all 45 of its length-comp rows are joint-sex, so
# the second of the two loops that predict a composition is the one that moved
# these numbers. Both GOA references reached these objectives from a cold
# phased fit AND from the previous reference's parameters, to ten decimals.
#
# WHAT THIS PINS, AND WHY IT NO LONGER RE-OPTIMIZES. The question golden exists
# to answer is "is this still the same likelihood". Re-fitting answered a second
# question as well -- "does a cold phased optimization find the lower of two
# minima on this machine" -- and that one has a platform-dependent answer:
# `goa_ss` has a second local minimum 52.9 units up, and a one-ULP change in a
# single log_F gradient element is enough for nlminb to reach it. The two GOA
# references moved together on the CI runners while reproducing exactly on local
# macOS, and the job that runs this file was red on `main` for weeks over a
# summation order. `goa_ms` has reached its own reference objective from both
# `goa_ss` basins, so it does not always follow `goa_ss` out of the lower one.
#
# The likelihood is now evaluated AT the reference parameters, which removes the
# optimizer from the gate entirely: `fit_mod(estimateMode = 3)` builds the object
# and evaluates without optimizing, so any change to the model moves the
# objective while a change to the optimizer's path cannot. Measured at 5.45.1:
# all four reproduce their pinned objective to 7e-12 absolute, which is the
# rounding of the 15-digit literal and not a model difference, at max|gradient|
# between 1.3e-11 and 5.0e-11 against a 1e-8 threshold. The multispecies pair was
# the open question -- predation iterates inside fit_mod() -- and the iteration
# reaches the same state from the reference parameters, so they pin as cleanly as
# the single-species pair.
#
# The cold-start path moved to tools/verify/verify-golden-cold-start.R. Regenerate
# the fixture with tools/verify/regenerate-golden-reference.R, and only when a
# model change is intended.
testthat::test_that("the likelihood at the reference parameters is unchanged", {
  testthat::skip_on_cran()
  # covr instruments the TMB model at -O0. The evaluation here no longer depends
  # on an optimizer path, so the historical reason for this skip is gone, but a
  # -O0 build's arithmetic is still not what the reference was taken under.
  testthat::skip_on_covr()
  testthat::skip_if_not_installed("TMB")
  testthat::skip_if_not_installed("Rceattle")

  # The objectives are literals HERE, not in the fixture, so a re-pin shows as
  # changed text in a diff rather than as changed bytes in a binary. The fixture
  # holds the parameters they were measured at, and nothing else.
  ref_obj <- c(ss     = 10241.0304272585,
               ms     = 10267.2478324443,
               goa_ss = 12866.8457276232,
               goa_ms = 12931.8602763619)

  ref <- readRDS(testthat::test_path("fixtures", "golden-reference.rds"))

  # Each reference's own configuration, matching the recipe the fixture script
  # fits: the multispecies pair warm-starts from its single-species MLEs and the
  # GOA multispecies fit holds M fixed.
  spec <- list(
    ss     = list(data = Rceattle::BS2017SS,  msmMode = 0, niter = 3),
    ms     = list(data = Rceattle::BS2017MS,  msmMode = 1, niter = 5),
    goa_ss = list(data = Rceattle::GOA2018SS, msmMode = 0, niter = 3),
    goa_ms = list(data = Rceattle::GOA2018SS, msmMode = 1, niter = 3))

  # A renamed or dropped key would otherwise reach fit_mod() as inits = NULL,
  # which silently COLD-STARTS and then reports a baffling objective.
  testthat::expect_setequal(names(ref), names(spec))

  for (m in names(spec)) {
    s <- spec[[m]]
    fit <- Rceattle::fit_mod(
      data_list = s$data, inits = ref[[m]]$params, file = NULL,
      estimateMode = 3, niter = s$niter, random_rec = FALSE,
      msmMode = s$msmMode, suitMode = 0,
      fit_control = Rceattle::fit_control(getsd = FALSE, verbose = 0))

    par <- fit$obj$par
    # 1e-10 relative is ~1e-06 nats here. Same-platform reproduction at fixed
    # parameters is exact, and TRAPS.md records these constants reproducing to
    # 16 digits across Windows and macOS/arm64 for the harder RE-OPTIMIZED
    # target, so this leaves six orders for a toolchain nobody has run while
    # staying far inside any real model change.
    testthat::expect_equal(as.numeric(fit$obj$fn(par)), ref_obj[[m]],
                           tolerance = 1e-10, info = m)
    # And the reference is still a stationary point of it, so the pin cannot
    # drift to a number that merely reproduces at a non-stationary point.
    testthat::expect_lt(max(abs(fit$obj$gr(par))), 1e-8,
                        label = paste0("max|gradient| for ", m))
  }
})

# =============================================================================
# Golden reference by CONFIGURATION.
#
# The four fits above share one configuration: plain multinomial compositions, a
# lognormal index, no tail accumulation, fixed recruitment. So the likelihood
# branches the ecosystem models actually run had no golden cover, and a change
# confined to one of them could not fail here. Plain Multinomial is not even the
# schema default for Comp_distribution -- MultinomialAFSC is -- so the branch a
# model gets when the column is left out was unpinned as well. Each block below
# switches on a single branch, on the same BS2017SS data, so a failure points at
# the branch rather than at the model.
#
# Still unpinned after this, and worth adding if they ever break: CAAL, length
# compositions, nonparametric selectivity, and any multispecies combination of
# the branches below -- both multispecies references run the default setup.
#
# Each pinned value was measured under exactly the fit_control settings its
# block uses, and checked for basin robustness first. A pin whose basin is not
# unique fails on another platform's optimizer path for reasons unrelated to any
# code change, which is what the multi-OS check already sees on the phased
# integration fits. For the three cheap fits that check was six jittered starts
# (sd = 0.1), which spread the objective by ~1e-11 relative, matching the four
# references above. The random-recruitment fit is too slow to jitter six times;
# its evidence is instead that the phased and unphased optimizer paths agree to
# 1e-13 relative -- path robustness rather than start-point robustness, which is
# weaker, so treat a failure there as worth investigating before re-pinning.
#
# Dirichlet-multinomial is pinned WITH a prior on theta, and cannot be pinned
# without one. BS2017SS's compositions do not identify the DM theta on their
# own: as theta grows the Dirichlet-multinomial tends to the multinomial, so
# with uninformative comps there is no interior optimum. Bare DM shows exactly
# that -- phased it stops at max|grad| ~ 2 on 'comp_weights' with the
# convergence diagnostic reporting FAIL, unphased it reaches only 2.9e-4, and
# phased and unphased land 3 objective units apart (3.2e-4 relative, ~300x the
# tolerance here), so a pinned value would track the phasing path rather than
# the model. Its jitter spread is 5.7e-8: passable today, but ~2000x looser
# than every other reference here and the first margin to go on another
# platform. The gamma prior below identifies theta instead of masking it --
# theta lands finite and per-fleet (0.54 to 17.0) rather than running to the
# multinomial limit, the gradient falls to 3.9e-11, and the jitter spread
# tightens to 1.7e-11, in line with the rest of this file. The prior path is
# itself untested elsewhere at the fit level, so this pin covers the linkage
# grammar's intercept-prior machinery as well as the DM likelihood.
# =============================================================================

golden_fit_control <- function(...) {
  Rceattle::fit_control(getsd = FALSE, verbose = 0, ...)
}

testthat::test_that("composition tail accumulation reproduces its pinned objective", {
  testthat::skip_on_cran()
  testthat::skip_on_covr()
  testthat::skip_if_not_installed("TMB")

  # Fold ages 1-2 into age 3 and the oldest two ages into age nages-2 on every
  # fleet, so both tails of the composition likelihood are exercised. The bin
  # columns are indices on the fleet's own dimension, so the old-tail bin is
  # taken per species rather than as one number.
  d <- Rceattle::BS2017SS
  spp <- d$fleet_control$Species
  d$fleet_control$Comp_accum_young <- 3L
  d$fleet_control$Comp_accum_old   <- as.integer(d$nages[spp] - 2L)

  fit <- Rceattle::fit_mod(
    data_list = d, inits = NULL, file = NULL, estimateMode = 0,
    random_rec = FALSE, msmMode = 0,
    fit_control = golden_fit_control(phase = TRUE, newtonsteps = 3))

  testthat::expect_equal(fit$opt$objective, 6667.9360362185, tolerance = 1e-6)
  testthat::expect_lt(max(abs(fit$obj$gr(fit$opt$par))), 1e-4)
})

testthat::test_that("the MVN and Normal index families reproduce their pinned objective", {
  testthat::skip_on_cran()
  testthat::skip_on_covr()
  testthat::skip_if_not_installed("TMB")

  d <- Rceattle::BS2017SS
  d$fleet_control$Index_distribution    <- "Lognormal"
  d$fleet_control$Index_distribution[4] <- "MVN"      # BT_Pollock, 36 years
  d$fleet_control$Index_distribution[7] <- "Normal"   # EIT_Pollock
  # AnalyticalArith is the q form the covariance likelihood is paired with (see
  # section 8.2b of ceattle.cpp), and the pairing EBS pollock's BTS survey runs.
  # Leaving q freely estimated instead is not a configuration anyone uses, and
  # it converges markedly worse -- see the note above the gradient check below.
  d$fleet_control$Catchability[4]       <- "AnalyticalArith"

  # Compound-symmetric Sigma on the OBSERVATION scale -- the covariance index
  # likelihood works on the natural scale, not the log scale. Built from the
  # fleet's own observations and log sds so it is deterministic and scaled like
  # the data it describes; rho = 0.3 makes the off-diagonals load-bearing, so a
  # change that ignored them would move the objective.
  i <- d$index_data[d$index_data$Fleet_code == 4, ]
  sds <- i$Observation * i$Log_sd
  R <- matrix(0.3, length(sds), length(sds))
  diag(R) <- 1
  Sigma <- diag(sds) %*% R %*% diag(sds)
  dimnames(Sigma) <- list(as.character(i$Year), as.character(i$Year))
  d$index_cov <- list(BT_Pollock = Sigma)

  # Unphased with heavy polishing: phasing leaves this configuration twice as
  # loose (4.8e-5 against 2.5e-5), and the extra Newton steps are what reach a
  # stationary point at all.
  fit <- Rceattle::fit_mod(
    data_list = d, inits = NULL, file = NULL, estimateMode = 0,
    random_rec = FALSE, msmMode = 0,
    fit_control = golden_fit_control(phase = FALSE, newtonsteps = 15,
                                     loopnum = 3))

  testthat::expect_equal(fit$opt$objective, 17567.4350624190, tolerance = 1e-6)
  # This fit converges less tightly than the others here, for a reason worth
  # recording rather than tuning away: index_log_q and rec_pars carry EQUAL
  # gradient at the optimum, which is the signature of the
  # q-versus-population-scale ridge -- raising catchability while lowering
  # abundance leaves the predicted index unchanged. Compound symmetry in Sigma
  # then softens precisely that direction, by 1 + (n-1)*rho = 11.5x here, which
  # is why it shows up under the covariance likelihood and not under the
  # lognormal reference.
  #
  # The gate is 1e-3 and not the 1e-4 the rest of the file uses, because on a
  # ridge this flat the gradient records where the optimizer STOPPED, which is
  # platform-dependent: 2.5e-5 on local macOS/arm64 and 3.5e-4 on ubuntu-latest
  # (deep-checks run 36433121293, 2026-09-28), which failed the job. The
  # objective is the pinned quantity and it reproduced on that same run to the
  # 1e-6 above; asserting 1e-4 here asserts the optimizer's stopping point, not
  # the model. A value above 1e-3 means it did not reach the ridge at all.
  testthat::expect_lt(max(abs(fit$obj$gr(fit$opt$par))), 1e-3)
})

testthat::test_that("Dirichlet-multinomial comps under a theta prior reproduce their pinned objective", {
  testthat::skip_on_cran()
  testthat::skip_on_covr()
  testthat::skip_if_not_installed("TMB")

  d <- Rceattle::BS2017SS
  d$fleet_control$Comp_distribution <- "DirichletMultinomial"

  # Prior-only process: the DM weights have no covariate or random-effect form,
  # so the intercept re-targets the log DM scalar and a gamma prior on the
  # natural theta falls out of the shared intercept-prior loop. gamma(2, 0.5)
  # matches the shape used in test-linkage-composition.R.
  cfun <- Rceattle::build_composition(linkages = list(
    theta_comp = Rceattle::linkage_spec(
      ~ 1, by = ~ fleet,
      priors = list(`(Intercept)` = gamma(2, 0.5)))))

  fit <- Rceattle::fit_mod(
    data_list = d, inits = NULL, file = NULL, estimateMode = 0,
    random_rec = FALSE, msmMode = 0, compFun = cfun,
    fit_control = golden_fit_control(phase = FALSE, newtonsteps = 3))

  testthat::expect_equal(fit$opt$objective, 9293.4046676646, tolerance = 1e-6)
  testthat::expect_lt(max(abs(fit$obj$gr(fit$opt$par))), 1e-4)

  # The prior has to identify theta, not merely regularise the objective: an
  # unidentified DM runs theta toward the multinomial limit. Finite, per-fleet
  # values are the evidence that it is pinned by data plus prior.
  theta <- exp(fit$opt$par[names(fit$opt$par) == "comp_weights"])
  testthat::expect_true(all(is.finite(theta)))
  testthat::expect_true(all(theta > 0.1 & theta < 100))
})

testthat::test_that("the default MultinomialAFSC composition likelihood reproduces its pinned objective", {
  testthat::skip_on_cran()
  testthat::skip_on_covr()
  testthat::skip_if_not_installed("TMB")

  # The branch a model gets when Comp_distribution is left out of fleet_control,
  # and the one EBS pollock runs. Phased and unphased agree to ten decimals here,
  # so the pin does not depend on the optimizer path.
  d <- Rceattle::BS2017SS
  d$fleet_control$Comp_distribution <- "MultinomialAFSC"

  fit <- Rceattle::fit_mod(
    data_list = d, inits = NULL, file = NULL, estimateMode = 0,
    random_rec = FALSE, msmMode = 0,
    fit_control = golden_fit_control(phase = TRUE, newtonsteps = 3))

  testthat::expect_equal(fit$opt$objective, 4272.2320896464, tolerance = 1e-6)
  testthat::expect_lt(max(abs(fit$obj$gr(fit$opt$par))), 1e-4)
})

testthat::test_that("random recruitment reproduces its pinned objective", {
  testthat::skip_on_cran()
  testthat::skip_on_covr()
  testthat::skip_if_not_installed("TMB")

  # The only golden cover of the Laplace path, which every random_rec = TRUE
  # assessment runs. It is also the slowest fit in the suite at ~4.5 minutes;
  # unphasing does not help (315 s, same optimum), so it stays phased.
  fit <- Rceattle::fit_mod(
    data_list = Rceattle::BS2017SS, inits = NULL, file = NULL,
    estimateMode = 0, random_rec = TRUE, msmMode = 0,
    fit_control = golden_fit_control(phase = TRUE, newtonsteps = 3))

  # as.numeric(): under the Laplace approximation the objective comes back
  # carrying the log-determinant's `logarithm` attribute, which expect_equal
  # compares and would fail on even though the value matches.
  testthat::expect_equal(as.numeric(fit$opt$objective), 10401.6243383277,
                         tolerance = 1e-6)
  # Marginal gradient, the random effects having been integrated out.
  testthat::expect_lt(max(abs(fit$obj$gr(fit$opt$par))), 1e-4)
})
